version: '3'
services:
  salesforce_fastapi_adenuniversity_edu_pa:
    build:
      context: .
      dockerfile:
        Dockerfile.test
    ports:
      - "9000:9000"
    restart: on-failure
    container_name: salesforce_fastapi_adenuniversity_edu_pa
    image: salesforce_fastapi_adenuniversity_edu_pa