COUNTRY_MAPPING = {
    'AF': 'Afganistán',
    'AFG': 'Afganistán',
    'AX': 'Islas de Åland',
    'ALA': 'Islas de Åland',
    'AL': 'Albania',
    'ALB': 'Albania',
    'DZ': 'Argelia',
    'DZA': 'Argelia',
    'AS': 'Samoa Americana',
    'ASM': 'Samoa Americana',
    'AD': 'Andorra',
    'AND': 'Andorra',
    'AO': 'Angola',
    'AGO': 'Angola',
    'AI': 'Anguila',
    'AIA': 'Anguila',
    'AQ': 'Antártida',
    'ATA': 'Antártida',
    'AG': 'Antigua y Barbuda',
    'ATG': 'Antigua y Barbuda',
    'AR': 'Argentina',
    'ARG': 'Argentina',
    'AM': 'Armenia',
    'ARM': 'Armenia',
    'AW': 'Aruba',
    'ABW': 'Aruba',
    'AU': 'Australia',
    'AUS': 'Australia',
    'AT': 'Austria',
    'AUT': 'Austria',
    'AZ': 'Azerbaiyán',
    'AZE': 'Azerbaiyán',
    'BS': 'Bahamas',
    'BHS': 'Bahamas',
    'BH': 'Baréin',
    'BHR': 'Baréin',
    'BD': 'Bangladesh',
    'BGD': 'Bangladesh',
    'BB': 'Barbados',
    'BRB': 'Barbados',
    'BY': 'Bielorrusia',
    'BLR': 'Bielorrusia',
    'BE': 'Bélgica',
    'BEL': 'Bélgica',
    'BZ': 'Belice',
    'BLZ': 'Belice',
    'BJ': 'Benín',
    'BEN': 'Benín',
    'BM': 'Bermuda',
    'BMU': 'Bermuda',
    'BT': 'Bután',
    'BTN': 'Bután',
    'BO': 'Bolivia',
    'BOL': 'Bolivia',
    'BQ': 'Bonaire, San Eustaquio y Saba',
    'BES': 'Bonaire, San Eustaquio y Saba',
    'BA': 'Bosnia y Herzegovina',
    'BIH': 'Bosnia y Herzegovina',
    'BW': 'Botsuana',
    'BWA': 'Botsuana',
    'BV': 'Isla Bouvet',
    'BVT': 'Isla Bouvet',
    'BR': 'Brasil',
    'BRA': 'Brasil',
    'IO': 'Territorio Británico del Océano Índico',
    'IOT': 'Territorio Británico del Océano Índico',
    'VG': 'Islas Vírgenes Británicas',
    'VGB': 'Islas Vírgenes Británicas',
    'BN': 'Brunei',
    'BRN': 'Brunei',
    'BG': 'Bulgaria',
    'BGR': 'Bulgaria',
    'BF': 'Burkina Faso',
    'BFA': 'Burkina Faso',
    'BI': 'Burundi',
    'BDI': 'Burundi',
    'KH': 'Camboya',
    'KHM': 'Camboya',
    'CM': 'Camerún',
    'CMR': 'Camerún',
    'CA': 'Canadá',
    'CAN': 'Canadá',
    'CV': 'Cabo Verde',
    'CPV': 'Cabo Verde',
    'KY': 'Islas Caimán',
    'CYM': 'Islas Caimán',
    'CF': 'República de África Central',
    'CAF': 'República de África Central',
    'TD': 'Chad',
    'TCD': 'Chad',
    'CL': 'Chile',
    'CHL': 'Chile',
    'CN': 'China',
    'CHN': 'China',
    'CX': 'Isla de Pascua',
    'CXR': 'Isla de Pascua',
    'CC': 'Islas Cocos',
    'CCK': 'Islas Cocos',
    'CO': 'Colombia',
    'COL': 'Colombia',
    'KM': 'Comoras',
    'COM': 'Comoras',
    'CK': 'Islas Cook',
    'COK': 'Islas Cook',
    'CR': 'Costa Rica',
    'CRI': 'Costa Rica',
    'HR': 'Croacia',
    'HRV': 'Croacia',
    'CU': 'Cuba',
    'CUB': 'Cuba',
    'CW': 'Curazao',
    'CUW': 'Curazao',
    'CY': 'Chipre',
    'CYP': 'Chipre',
    'CZ': 'República Checa',
    'CZE': 'República Checa',
    'CD': 'República Democrática del Congo',
    'COD': 'República Democrática del Congo',
    'DK': 'Dinamarca',
    'DNK': 'Dinamarca',
    'DJ': 'Yibuti',
    'DJI': 'Yibuti',
    'DM': 'Dominica',
    'DMA': 'Dominica',
    'DO': 'República Dominicana',
    'DOM': 'República Dominicana',
    'TL': 'Timor Oriental',
    'TLS': 'Timor Oriental',
    'EC': 'Ecuador',
    'ECU': 'Ecuador',
    'EG': 'Egipto',
    'EGY': 'Egipto',
    'SV': 'El Salvador',
    'SLV': 'El Salvador',
    'GQ': 'Guinea Ecuatorial',
    'GNQ': 'Guinea Ecuatorial',
    'ER': 'Eritrea',
    'ERI': 'Eritrea',
    'EE': 'Estonia',
    'EST': 'Estonia',
    'ET': 'Etiopía',
    'ETH': 'Etiopía',
    'FK': 'Islas Malvinas',
    'FLK': 'Islas Malvinas',
    'FO': 'Islas Faroe',
    'FRO': 'Islas Faroe',
    'FJ': 'Fiji',
    'FJI': 'Fiji',
    'FI': 'Finlandia',
    'FIN': 'Finlandia',
    'FR': 'Francia',
    'FRA': 'Francia',
    'GF': 'Guayana Francesa',
    'GUF': 'Guayana Francesa',
    'PF': 'Polinesia Francesa',
    'PYF': 'Polinesia Francesa',
    'TF': 'Territorios Australes Franceses',
    'ATF': 'Territorios Australes Franceses',
    'GA': 'Gabón',
    'GAB': 'Gabón',
    'GM': 'Gambia',
    'GMB': 'Gambia',
    'GE': 'Georgia',
    'GEO': 'Georgia',
    'DE': 'Alemania',
    'DEU': 'Alemania',
    'GH': 'Ghana',
    'GHA': 'Ghana',
    'GI': 'Gibraltar',
    'GIB': 'Gibraltar',
    'GR': 'Grecia',
    'GRC': 'Grecia',
    'GL': 'Groenlandia',
    'GRL': 'Groenlandia',
    'GD': 'Granada',
    'GRD': 'Granada',
    'GP': 'Guadalupe',
    'GLP': 'Guadalupe',
    'GU': 'Guam',
    'GUM': 'Guam',
    'GT': 'Guatemala',
    'GTM': 'Guatemala',
    'GG': 'Guernsey',
    'GGY': 'Guernsey',
    'GN': 'Guinea',
    'GIN': 'Guinea',
    'GW': 'Guinea-Bissau',
    'GNB': 'Guinea-Bissau',
    'GY': 'Guyana',
    'GUY': 'Guyana',
    'HT': 'Haití',
    'HTI': 'Haití',
    'HM': 'Islas Heard y McDonald',
    'HMD': 'Islas Heard y McDonald',
    'HN': 'Honduras',
    'HND': 'Honduras',
    'HK': 'Hong Kong',
    'HKG': 'Hong Kong',
    'HU': 'Hungría',
    'HUN': 'Hungría',
    'IS': 'Islandia',
    'ISL': 'Islandia',
    'IN': 'India',
    'IND': 'India',
    'ID': 'Indonesia',
    'IDN': 'Indonesia',
    'IR': 'Irán',
    'IRN': 'Irán',
    'IQ': 'Iraq',
    'IRQ': 'Iraq',
    'IE': 'Irlanda',
    'IRL': 'Irlanda',
    'IM': 'Isla de Man',
    'IMN': 'Isla de Man',
    'IL': 'Israel',
    'ISR': 'Israel',
    'IT': 'Italia',
    'ITA': 'Italia',
    'CI': 'Costa de Marfil',
    'CIV': 'Costa de Marfil',
    'JM': 'Jamaica',
    'JAM': 'Jamaica',
    'JP': 'Japón',
    'JPN': 'Japón',
    'JE': 'Jersey',
    'JEY': 'Jersey',
    'JO': 'Jordania',
    'JOR': 'Jordania',
    'KZ': 'Kazajistán',
    'KAZ': 'Kazajistán',
    'KE': 'Kenia',
    'KEN': 'Kenia',
    'KI': 'Kiribati',
    'KIR': 'Kiribati',
    'XK': 'Kosovo',
    'XKX': 'Kosovo',
    'KW': 'Kuwait',
    'KWT': 'Kuwait',
    'KG': 'Kirguistán',
    'KGZ': 'Kirguistán',
    'LA': 'Laos',
    'LAO': 'Laos',
    'LV': 'Letonia',
    'LVA': 'Letonia',
    'LB': 'Líbano',
    'LBN': 'Líbano',
    'LS': 'Lesoto',
    'LSO': 'Lesoto',
    'LR': 'Liberia',
    'LBR': 'Liberia',
    'LY': 'Libia',
    'LBY': 'Libia',
    'LI': 'Liechtenstein',
    'LIE': 'Liechtenstein',
    'LT': 'Lituania',
    'LTU': 'Lituania',
    'LU': 'Luxemburgo',
    'LUX': 'Luxemburgo',
    'MO': 'Macao',
    'MAC': 'Macao',
    'MG': 'Madagascar',
    'MDG': 'Madagascar',
    'MW': 'Malaui',
    'MWI': 'Malaui',
    'MY': 'Malasia',
    'MYS': 'Malasia',
    'MV': 'Maldivas',
    'MDV': 'Maldivas',
    'ML': 'Malí',
    'MLI': 'Malí',
    'MT': 'Malta',
    'MLT': 'Malta',
    'MH': 'Islas Marshall',
    'MHL': 'Islas Marshall',
    'MQ': 'Martinica',
    'MTQ': 'Martinica',
    'MR': 'Mauritania',
    'MRT': 'Mauritania',
    'MU': 'Mauricio',
    'MUS': 'Mauricio',
    'YT': 'Mayotte',
    'MYT': 'Mayotte',
    'MX': 'México',
    'MEX': 'México',
    'FM': 'Micronesia',
    'FSM': 'Micronesia',
    'MD': 'Moldavia',
    'MDA': 'Moldavia',
    'MC': 'Mónaco',
    'MCO': 'Mónaco',
    'MN': 'Mongolia',
    'MNG': 'Mongolia',
    'ME': 'Montenegro',
    'MNE': 'Montenegro',
    'MS': 'Montserrat',
    'MSR': 'Montserrat',
    'MA': 'Marruecos',
    'MAR': 'Marruecos',
    'MZ': 'Mozambique',
    'MOZ': 'Mozambique',
    'MM': 'Myanmar',
    'MMR': 'Myanmar',
    'NA': 'Namibia',
    'NAM': 'Namibia',
    'NR': 'Nauru',
    'NRU': 'Nauru',
    'NP': 'Nepal',
    'NPL': 'Nepal',
    'NL': 'Países Bajos',
    'NLD': 'Países Bajos',
    'NC': 'Nueva Caledonia',
    'NCL': 'Nueva Caledonia',
    'NZ': 'Nueva Zelanda',
    'NZL': 'Nueva Zelanda',
    'NI': 'Nicaragua',
    'NIC': 'Nicaragua',
    'NE': 'Níger',
    'NER': 'Níger',
    'NG': 'Nigeria',
    'NGA': 'Nigeria',
    'NU': 'Niue',
    'NIU': 'Niue',
    'NF': 'Isla Norfolk',
    'NFK': 'Isla Norfolk',
    'KP': 'Corea del Norte',
    'PRK': 'Corea del Norte',
    'MK': 'Macedonia del Norte',
    'MKD': 'Macedonia del Norte',
    'MP': 'Islas Marianas del Norte',
    'MNP': 'Islas Marianas del Norte',
    'NO': 'Noruega',
    'NOR': 'Noruega',
    'OM': 'Omán',
    'OMN': 'Omán',
    'PK': 'Pakistán',
    'PAK': 'Pakistán',
    'PW': 'Palaos',
    'PLW': 'Palaos',
    'PS': 'Palestina',
    'PSE': 'Palestina',
    'PA': 'Panamá',
    'PAN': 'Panamá',
    'PG': 'Papúa Nueva Guinea',
    'PNG': 'Papúa Nueva Guinea',
    'PY': 'Paraguay',
    'PRY': 'Paraguay',
    'PE': 'Perú',
    'PER': 'Perú',
    'PH': 'Filipinas',
    'PHL': 'Filipinas',
    'PN': 'Pitcairn',
    'PCN': 'Pitcairn',
    'PL': 'Polonia',
    'POL': 'Polonia',
    'PT': 'Portugal',
    'PRT': 'Portugal',
    'PR': 'Puerto Rico',
    'PRI': 'Puerto Rico',
    'QA': 'Catar',
    'QAT': 'Catar',
    'CG': 'República del Congo',
    'COG': 'República del Congo',
    'RE': 'Reunión',
    'REU': 'Reunión',
    'RO': 'Rumania',
    'ROU': 'Rumania',
    'RU': 'Rusia',
    'RUS': 'Rusia',
    'RW': 'Ruanda',
    'RWA': 'Ruanda',
    'BL': 'San Bartolomé',
    'BLM': 'San Bartolomé',
    'SH': 'Santa Elena, Ascensión y Tristán de Acuña',
    'SHN': 'Santa Elena, Ascensión y Tristán de Acuña',
    'KN': 'San Cristóbal y Nieves',
    'KNA': 'San Cristóbal y Nieves',
    'LC': 'Santa Lucía',
    'LCA': 'Santa Lucía',
    'MF': 'San Martín',
    'MAF': 'San Martín',
    'PM': 'San Pedro y Miquelón',
    'SPM': 'San Pedro y Miquelón',
    'VC': 'San Vicente y las Granadinas',
    'VCT': 'San Vicente y las Granadinas',
    'WS': 'Samoa',
    'WSM': 'Samoa',
    'SM': 'San Marino',
    'SMR': 'San Marino',
    'ST': 'Santo Tomé y Príncipe',
    'STP': 'Santo Tomé y Príncipe',
    'SA': 'Arabia Saudita',
    'SAU': 'Arabia Saudita',
    'SN': 'Senegal',
    'SEN': 'Senegal',
    'RS': 'Serbia',
    'SRB': 'Serbia',
    'SC': 'Seychelles',
    'SYC': 'Seychelles',
    'SL': 'Sierra Leona',
    'SLE': 'Sierra Leona',
    'SG': 'Singapur',
    'SGP': 'Singapur',
    'SX': 'Sint Maarten',
    'SXM': 'Sint Maarten',
    'SK': 'Eslovaquia',
    'SVK': 'Eslovaquia',
    'SI': 'Eslovenia',
    'SVN': 'Eslovenia',
    'SB': 'Islas Salomón',
    'SLB': 'Islas Salomón',
    'SO': 'Somalia',
    'SOM': 'Somalia',
    'ZA': 'Sudáfrica',
    'ZAF': 'Sudáfrica',
    'GS': 'Islas Georgias del Sur y Sandwich del Sur',
    'SGS': 'Islas Georgias del Sur y Sandwich del Sur',
    'KR': 'Corea del Sur',
    'KOR': 'Corea del Sur',
    'SS': 'Sudán del Sur',
    'SSD': 'Sudán del Sur',
    'ES': 'España',
    'ESP': 'España',
    'LK': 'Sri Lanka',
    'LKA': 'Sri Lanka',
    'SD': 'Sudán',
    'SDN': 'Sudán',
    'SR': 'Surinam',
    'SUR': 'Surinam',
    'SJ': 'Svalbard y Jan Mayen',
    'SJM': 'Svalbard y Jan Mayen',
    'SZ': 'Suazilandia',
    'SWZ': 'Suazilandia',
    'SE': 'Suecia',
    'SWE': 'Suecia',
    'CH': 'Suiza',
    'CHE': 'Suiza',
    'SY': 'Siria',
    'SYR': 'Siria',
    'TW': 'Taiwán',
    'TWN': 'Taiwán',
    'TJ': 'Tayikistán',
    'TJK': 'Tayikistán',
    'TZ': 'Tanzania',
    'TZA': 'Tanzania',
    'TH': 'Tailandia',
    'THA': 'Tailandia',
    'TG': 'Togo',
    'TGO': 'Togo',
    'TK': 'Tokelau',
    'TKL': 'Tokelau',
    'TO': 'Tonga',
    'TON': 'Tonga',
    'TT': 'Trinidad y Tobago',
    'TTO': 'Trinidad y Tobago',
    'TN': 'Túnez',
    'TUN': 'Túnez',
    'TR': 'Turquía',
    'TUR': 'Turquía',
    'TM': 'Turkmenistán',
    'TKM': 'Turkmenistán',
    'TC': 'Islas Turcas y Caicos',
    'TCA': 'Islas Turcas y Caicos',
    'TV': 'Tuvalu',
    'TUV': 'Tuvalu',
    'UG': 'Uganda',
    'UGA': 'Uganda',
    'UA': 'Ucrania',
    'UKR': 'Ucrania',
    'AE': 'Emiratos Árabes Unidos',
    'ARE': 'Emiratos Árabes Unidos',
    'GB': 'Reino Unido',
    'GBR': 'Reino Unido',
    'US': 'Estados Unidos',
    'USA': 'Estados Unidos',
    'UM': 'Islas menores alejadas de los Estados Unidos',
    'UMI': 'Islas menores alejadas de los Estados Unidos',
    'UY': 'Uruguay',
    'URY': 'Uruguay',
    'UZ': 'Uzbekistán',
    'UZB': 'Uzbekistán',
    'VU': 'Vanuatu',
    'VUT': 'Vanuatu',
    'VA': 'Ciudad del Vaticano',
    'VAT': 'Ciudad del Vaticano',
    'VE': 'Venezuela',
    'VEN': 'Venezuela',
    'VN': 'Vietnam',
    'VNM': 'Vietnam',
    'WF': 'Wallis y Futuna',
    'WLF': 'Wallis y Futuna',
    'EH': 'Sáhara Occidental',
    'ESH': 'Sáhara Occidental',
    'YE': 'Yemen',
    'YEM': 'Yemen',
    'ZM': 'Zambia',
    'ZMB': 'Zambia',
    'ZW': 'Zimbabue',
    'ZWE': 'Zimbabue'
}


def normalize_the_country(country_code: str, country_mapping=COUNTRY_MAPPING) -> str:
    return country_mapping.get(country_code, '')
